#!/bin/bash

# CONFIGURATION:

# Set web_browser_command to your browser's executable file

# Mozilla Firefox, installed in /opt/firefox
web_browser_command="/opt/firefox/firefox"

BINDIR=/home/jay/.bin
ELFDIR=/home/jay/.bin/elf

# END OF CONFIGURATION

live_show_url="https://changelog.com/gotime"

cmdname=`basename $0`

if [ $# -gt 1 ]
then
	echo "$cmdname: bad arguments"
	echo "usage:  $cmdname [ Go-Duration ]"
	echo "Without an argument, the show time is scraped from"
	echo "	$live_show_url and the duration is set automatically."
	echo "If an argument is supplied, it is interpreted as a Go time.Duration"
	echo "	string.	For example, 2h23s means 2 hours and 23 seconds."
	exit 2
elif [ $# -eq 1 ]
then
	duration="$1"
else
	start_time=`$BINDIR/gotime-scraper`

	if [ $? -eq 0 ]
	then
		duration=`$ELFDIR/gotime2dur $start_time`
		if [ $? -ne 0 ]
		then
			exit 2
		fi
	else
		exit 2
	fi
fi

$ELFDIR/timer "$duration" || exit

nohup "$web_browser_command" >/dev/null 2>&1 "$live_show_url" &
sleep 5
