#!/bin/bash

# Customization:
# Set term to the name of the virtual terminal program you want to use,
# and set term_opts to the options it needs

term=konsole

# The --profile argument for konsole uses this profile:
# General->Profile name: Timer
# General->Command: /bin/bash
# General->Columns: 13
# General->Rows: 2
# Appearance->Color Scheme: Black on White
# Appearance->Font: Monospace, Text size: 24
# Scrolling->Scroll Bar: Hide
# Advanced->Cursor->Custom cursor color: white (#fff)

term_opts="--profile Timer --hide-menubar --hide-tabbar -p ScrollBarPosition=2 -p TerminalRows=2 -p TerminalColumns=13"

if [ $# -gt 1 ]
then
	echo "gotime: too many arguments"
	echo "usage: gotime [ Duration ]"
	exit 1
fi

$term 2>/dev/null $term_opts -e gotime-cli "$@"
